In [ ]:
Q4. Build a logistic regression model to predict whether a student gets 
admitted into a university using appropriate dataset. 

In [3]:
#Import Necessary Libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [4]:
#Import the dataset and convert it into a dataframe 
df = pd.read_csv(r'student_admission_dataset.csv')

# Features (X) and target (y)
X = df[['GPA', 'SAT_Score', 'Extracurricular_Activities']]
y = df['Admission_Status']

# Splitting the dataset into training and testing sets (80-20 split)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features for better performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Building the Logistic Regression model
model = LogisticRegression()
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

# Output results
print(f'Accuracy: {accuracy}\n')
print(f'Confusion Matrix:\n{conf_matrix}\n')
print(f'Classification Report:\n{class_report}')

Accuracy: 0.34

Confusion Matrix:
[[8 3 3]
 [6 7 5]
 [8 8 2]]

Classification Report:
              precision    recall  f1-score   support

    Accepted       0.36      0.57      0.44        14
    Rejected       0.39      0.39      0.39        18
  Waitlisted       0.20      0.11      0.14        18

    accuracy                           0.34        50
   macro avg       0.32      0.36      0.33        50
weighted avg       0.31      0.34      0.32        50



In [8]:
def predict_admission(model, scaler):
    print("\n--- Predict Admission Status for a New Student ---")

    # Collect user input for prediction
    gpa = float(input("Enter GPA: "))
    sat_score = float(input("Enter SAT Score: "))
    extra_activities = float(input("Enter Extracurricular Activities Score (e.g., 0-5): "))

    print("\nThe input GPA is :", gpa)
    print("The input SAT Score :", sat_score)
    print("The input Extracurricular Activities Score :", extra_activities)

    # Standardize the input data
    new_data = scaler.transform([[gpa, sat_score, extra_activities]])
    prediction = model.predict(new_data)

    # Display the prediction result
    if prediction[0] == 1:
        print("Prediction: The student is likely to be ADMITTED.")
    else:
        print("Prediction: The student is NOT likely to be admitted.")
    print("\n")
    

# Example usage:
predict_admission(model, scaler)
predict_admission(model, scaler)



--- Predict Admission Status for a New Student ---


/Users/rajesh/Library/Python/3.9/lib/python/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(



The input GPA is : 3.94
The input SAT Score : 998.0
The input Extracurricular Activities Score : 4.0
Prediction: The student is NOT likely to be admitted.



--- Predict Admission Status for a New Student ---

The input GPA is : 5.0
The input SAT Score : 1000.0
The input Extracurricular Activities Score : 1.0
Prediction: The student is NOT likely to be admitted.




/Users/rajesh/Library/Python/3.9/lib/python/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
